### ISSUE TITLE
error: ‘strncmp’ is not a member of ‘std’

### ISSUE THREAD

**Issue by tiramisutes** [msauria/minUniqueKmer#1]
Dear,
I get follows stderr when making this software. I'm not a family of c/c++ and don't know how to resulution this problem.
```
g++ -pthread -std=c++11 -o bin/meanKmerCoverage meanKmerCoverage.cpp -ICTPL
meanKmerCoverage.cpp: In function ‘int main(int, char**)’:
meanKmerCoverage.cpp:159:16: error: ‘strncmp’ is not a member of ‘std’
       if (std::strncmp(argv[apos], "-t", 2) == 0)
                ^~~~~~~
make: *** [meanKmerCoverage] Error 1
```
Any help is much appreciated.
Thanks.

Best regards,

**Comment by msauria** [comment]
Hi,

This appears to have resulted from a missing include statement. I've updated the repo. Please pull the latest commit and try again. I believe this should resolve the issue.

Cheers

**Comment by tiramisutes** [comment]
Thanks. It was compiled successfully.
