### ISSUE TITLE
some chromosomal information is missing

### ISSUE THREAD

**Issue by tiramisutes** [msauria/minUniqueKmer#2]
Hi,
I found some chromosomal information is missing when run command as follows. There are a total of 10 chromosomes in my study species. But the finally output file (`output.wig`) only have 9 chromosomes and the 10th chromosome is missing.
```
find_minUniqueKmer.sh genome.fa 10
meanKmerCoverage 100 input.mul.wig input.mur.wig > output.wig
```

When I checked the output file `input.mul.wig` and `input.mur.wig`, the Chr10 only have `start=1` and `step=1`. But there is some data that comes after this row.
```
fixedStep chrom=Chr9 start=1 step=1
fixedStep chrom=Chr9  start=32226349 step=1
fixedStep chrom=Chr10 start=1 step=1
```

Any help is much appreciated.
Thanks.

Best regards,

**Comment by msauria** [comment]
This is strange. So there is an entry for chr10 ("fixedStep chrom=Chr10
start=1 step=1"), but nothing after it? How long is chr10? One possibility
is that the entire chromosome is repetitive, although this seems very
unlikely. Unfortunately, I don't have an immediate idea of what is wrong.
If you are willing to share the genome.fa file with me, I'm happy to take a
look.

-Mike

**Comment by tiramisutes** [comment]
I have sent an email including the genome file and description information to your Gmail. Please check it and thanks again.

**Comment by msauria** [comment]
I just wanted to let you know that I have not forgotten this. I will be
back in the office tomorrow and figure out the issue.

**Comment by tiramisutes** [comment]
Thanks. You may finish your work on hand first. Just help me when you have time.
